Fixing "Undefined variable $backURL" in enforeLogin function
silverstripe/silverstripe-realme pull request #100
Opened 2023-04-19 04:33 UTC by LABCAT

Note, there is already a pull request for this issue which looks to be abandoned:
https://github.com/silverstripe/silverstripe-realme/pull/81

This pull request is a simpler fix which doesn't remove the call to validSiteURL.  

Unfortunately, I also do not have time to contribute a unit test to the repository.

2023-04-27 03:17 UTC, GuySartorelli requested changes
Please just swap all instances of `$backURL` to `$backUrl` - it seems clear they were all meant to be the same variable.

2023-04-28 02:28 UTC, LABCAT commented
@GuySartorelli I have updated the merge request as suggested.

2023-04-28 03:10 UTC, GuySartorelli approved these changes

2023-04-28 03:13 UTC, GuySartorelli commented
Nice, thanks! I've retargetted this PR to the `4.4` branch so it can be released as a patch. Can you please reset the PR to not include the extra commits retargetted it has picked up?
Easiest way is probably to do this:

```sh
git branch -D patch-1
git checkout 4.4
git checkout -b patch-1
git cherry-pick 3a544fb 6618825
git push patch-1 --force
```

This will delete your current branch locally, then recreate a new branch with the same name, but this time based on the `4.4` branch. It'll then cherry-pick in your original commits, and push them to the remote, which will update this PR.

2023-04-30 20:57 UTC, LABCAT commented
@GuySartorelli branch has now been rebased onto 4.4 and ready to merge.

2023-04-30 21:08 UTC, GuySartorelli approved these changes

2023-04-30 21:08 UTC, GuySartorelli commented
Awesome, thanks for that. Just letting CI run and will merge on green.

2023-04-30 21:11 UTC, merged

2023-04-30 21:11 UTC, GuySartorelli commented
Released as [4.4.1](https://github.com/silverstripe/silverstripe-realme/releases/tag/4.4.1)