Pulls/4.0/no undefined var
silverstripe/silverstripe-realme pull request #55
Opened 2020-01-16 04:47 UTC by NightJar

Support new methods of data transfer (RealMe now transmits in JSON values for the SAML attribute keys for new environments), and correct behaviour of assert style authentication - so the module can be used with PHP 7.2+ and does not behave wastefully with regards to storage space for Member records.

2020-02-20 03:17 UTC, dnsl48 requested changes

2020-02-20 03:43 UTC, NightJar commented on src/Authenticator/LoginHandler.php
> +                    if ($realMeServiceConfig->get('integration_type') === RealMeService::TYPE_LOGIN) {
Whoops, pretty sure this should be `RealMeService::TYPE_LOGIN`

2020-02-25 01:16 UTC, dnsl48 commented
Tested with PHP 7.1, 7.2 and 7.3 on the following integrations:
 - MTS Login
 - MTS Assert (XML)
 - ITE Login
 - ITE Assert (JSON)

2020-02-25 01:17 UTC, dnsl48 approved these changes
Well done!

2020-02-25 01:20 UTC, merged